### ISSUE TITLE
Max version of attrs

### ISSUE THREAD

**Issue by cheginit** [requests-cache/aiohttp-client-cache#131]
### The problem
I was updating my package's conda-forge feedstock and noticed that it [failed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=544093&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d). When I diagnosed the problem the issue was with `attrs` version:

```bash
aiohttp-client-cache 0.7.2 has requirement attrs<22.0,>=21.2, but you have attrs 22.1.0.
```

I looked into dependencies of `aiohttp-client-cache` and noticed that there's no upper limit for `attrs` in the `pyproject.toml` file instead the limit is set in the `poetry.lock` file at this [line](https://github.com/requests-cache/aiohttp-client-cache/blob/5c93ad59a8373d5a88c74c6fe90789685d701e47/poetry.lock#L493).

I wonder if this is intentional or you missed updating the poetry lock file before the new release. Also, there is no `attrs` upper limit in `aiohttp-client-cache` feedstock file at this [line](https://github.com/conda-forge/aiohttp-client-cache-feedstock/blob/258cfbd60a05a4efc17f362b32528b0b5f18e2ce/recipe/meta.yaml#L29).

### Expected behavior
If the upper limit is intentional `pip check` shouldn't fail.

### Steps to reproduce the behavior
Check the log of my package's feedstock repo [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=544093&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d).

### Workarounds
If the upper limit is intentional both the `meta.yml` and `pyproject.toml` files need to be updated.

### Environment
- aiohttp-client-cache version: `0.7.2`
- Python version: conda-forge feedstock CI
- Platform: conda-forge feedstock CI

**Comment by JWCook** [comment]
Thanks for the detailed report. Currently this line: https://github.com/requests-cache/aiohttp-client-cache/blob/5c93ad59a8373d5a88c74c6fe90789685d701e47/pyproject.toml#L35
Does set an upper bound on the attrs version. I didn't realize that would affect the conda package.

I think attrs has a pretty good track record of not breaking backwards-compatibility, so I would be fine with removing that constraint. I'll get another patch release out soon.

**Comment by cheginit** [comment]
Ah, I see. I thought that caret acts like `>=`. It seems that `pip check` stage in my `metal.yml` fails.

Thanks for addressing the issue.

**Comment by cheginit** [comment]
I just reran the checks for my package and it worked using 0.7.3 version. Thanks for the quick fix.
