### ISSUE TITLE
Possible deadlock with SQLite backend

### ISSUE THREAD

**Issue by JWCook** [requests-cache/aiohttp-client-cache#147]
See: https://github.com/requests-cache/aiohttp-client-cache/discussions/146

<div type='discussions-op-text'>

<sup>Originally posted by **AIGeneratedUsername** January  4, 2023</sup>
**0.7.3** version works fine, but when I install **0.8.0**, my Pytest tests results in:

```
======================================================== test session starts =========================================================
platform linux -- Python 3.10.9, pytest-7.2.0, pluggy-1.0.0

[A LIST OF MY TESTS HERE, NOT IMPORTANT]

================================================= 1 passed, 208 deselected in 4.16s ==================================================
```

In other words, after all tests the session hangs forever.
</div>

**Comment by AIGeneratedUsername** [comment]
Thank you. The described problem was fixed in `0.8.1`.
