### ISSUE TITLE
Boolean parameters make cache lookups fail

### ISSUE THREAD

**Issue by Kigstn** [requests-cache/aiohttp-client-cache#149]
### The problem
_A description of what the bug is, including a complete traceback (if applicable)_
Booleans are valid url parameters, but when using yarl to add them to the url for cache lookups the conversion fails:
https://github.com/aio-libs/yarl#why-isnt-boolean-supported-by-the-url-query-api

--> `yarl\_url.py:916 in _query_var: TypeError: Invalid variable type: value should be str, int or float, got False of type <class 'bool'>`

### Expected behavior
_A description of what you expected to happen_
The url parameter gets converted to a string before, for example. I don't think it matters too much what exactly is done, since you only need the conversion for internal lookups.

### Steps to reproduce the behavior
_With a complete code example, if possible_
Try to cache a request which has a boolean parameter

### Workarounds
_Is there an existing workaround for this issue?_
None I can think of

### Environment
- aiohttp-client-cache version: [e.g. `0.3.0`] 0.7.3
- Python version: [e.g. `3.9`] 3.11
- Platform: [e.g. Debian 10] Win10 + Ubuntu

**Comment by AIGeneratedUsername** [comment]
This is similar to https://github.com/requests-cache/aiohttp-client-cache/issues/105 but all required types should be already handled properly.

Could you please share a small sample code that works with `aiohttp`, but does not work with `aiohttp-client-cache`?

**Comment by Kigstn** [comment]
Ah, actually my bad. I derped and missed that the params need to be used for actual queries as well, so aiohttp won't work too. 
I'll close the issue and instead work on getting my vars cleaned up before using them :)

**Comment by JWCook** [comment]
Thanks for helping out, @AIGeneratedUsername!

@Kigstn No worries, let me know if you run into any other problems.
