### ISSUE TITLE
Memory leak with `redis` backend when `hiredis` is installed

### ISSUE THREAD

**Issue by jamestrousdale** [requests-cache/aiohttp-client-cache#153]
### The problem
Not so much a bug with `aiohttp-client-cache` per se, but it can be impacted by upstream bugs. There may also be a chance for optimization.

I filed https://github.com/redis/redis-py/issues/2741 against apparent memory leaks from `redis-py` when `hiredis` is installed.

As part of the investigation, I realized that even if we provide our own `Redis` connection instance to `aiohttp-client-cache`, it still takes the liberty to close the connection on our behalf after the HTTP request session ends.

I think that if the connection object is supplied (as opposed to the `redis` URL), then `aiohttp-client-cache` should not close the `Redis` connection, as the client code may want to continue to use that connection object/associated connection pool.

The problem is not big in one-off scripts, but in a long-running microservice (where we discovered the issue originally), it will definitely lead to OOMs.

### Expected behavior
If the user supplies a `Redis` object in lieu of the URL, don't close connections.

### Steps to reproduce the behavior
See https://github.com/redis/redis-py/issues/2741 - the connections created as part of the `RedisBackend` objects needed for Redis-backed response caching should make it obvious how to reproduce in `aiohttp-client-cache`

### Workarounds
Don't use `hiredis` when using `redis` backend

### Environment
- aiohttp-client-cache version: `0.8.1`
- Python version: `3.11.3`
- Platform: Reproduced on both MacOS (arm64) and Linux (amd64)

**Comment by jamestrousdale** [comment]
Thanks for the response @JWCook 

I was wondering if it might make sense to set a flag `self._external_connection = True` on the `RedisCache` instance if the user supplies the connection, and if so, chase the `close` implementation for `RedisCache` to something like

```python
    async def close(self):
        if self._connection and not self._external_connection:
            await self._connection.close()
            self._connection = None
```

This seems like a `redis`-specific issue for this library and if I understand right, the impact would be contained.

**Comment by jamestrousdale** [comment]
FYI seems the latest release of `hiredis` `2.2.3` has already resolved the observed leak.

I do still think it might be good to allow users the option to manage the connection if they choose by supplying their own connection object which isn't destroyed on teardown.

**Comment by JWCook** [comment]
Basically I'd like to do whatever is least surprising to users. After considering about it some more, I think auto-closing backend connections probably isn't obvious behavior. 

Since I introduced this change fairly recently (0.8.1), I think it might be best to revert it, and leave it up to the user to close those backend connections if they want (same behavior as <=0.8.0). Does that sound reasonable to you?

**Comment by JWCook** [comment]
I added an `autoclose` option, which will be available in the next patch release.
