### ISSUE TITLE
`expire_after` actually doesn't remove key from cache backend (RedisBackend). Is this intended?

### ISSUE THREAD

**Issue by lb1mg** [requests-cache/aiohttp-client-cache#161]
expiring keys is working in practice but keys still remain in Redis and maybe as a result `session.cache.get_urls()` returns all urls from way back even those that have expired.
Kindly correct me if I am doing something wrong. Thanks

**Comment by JWCook** [comment]
That's the intended behavior for now. Currently cache expiration just means the response is "stale", and it isn't automatically deleted, it's just overwritten when a fresh response is retrieved. These can be explicitly removed with [`session.cache.delete_expired_responses()`](https://aiohttp-client-cache.readthedocs.io/en/stable/modules/aiohttp_client_cache.backends.base.html#aiohttp_client_cache.backends.base.CacheBackend.delete_expired_responses).

What you're probably looking for is backend-specific TTL integration (`EXPIRE` command for Redis, TTL index for MongoDB, etc.). [requests-cache has this](https://requests-cache.readthedocs.io/en/stable/user_guide/backends/redis.html#expiration), for example, but it hasn't been implemented for this library.

**Comment by lb1mg** [comment]
Thanks for clarification! 
Flagging cached url "stale" for expiration is great but `session.cache.get_urls()` should either:
1) return only unexpired cached urls 
2) or should provide an option for it 
as getting all urls (mixed with stale ones) from the beginning doesn't seem to be much helpful.
`session.cache.get_urls(include_stale=False)` : maybe something like this.

Well, for TTL I guess it's okay as it can be manually set (at least in case of Redis).

**Comment by JWCook** [comment]
Another thing worth noting is that the relationship between cached response expiration (aka "staleness") and backend expiration (aka "TTL") becomes a little fuzzier if conditional requests (#79) and `Cache-Control: stale-if-error` (#39) are implemented, since those introduce conditions where stale responses can be reused.
