### ISSUE TITLE
Feature request: Update badge to show build status of main branch

### ISSUE THREAD

**Issue by netomi** [requests-cache/aiohttp-client-cache#190]
### Feature description

You should update the build status badge to this link:

https://github.com/requests-cache/aiohttp-client-cache/actions/workflows/build.yml/badge.svg?branch=main

We want to see the status of the main branch, also GitHub caches things quite aggressively, so it might stay red for a while if a build failed.

**Comment by JWCook** [comment]
Done. Thanks for the tip!
