### ISSUE TITLE
Update ".github/workflows/build.yml" with dependabot

### ISSUE THREAD

**Issue by olk-m** [requests-cache/aiohttp-client-cache#208]
I noticed an outdated `3.11.4`  in `python-version: ['3.8', '3.9', '3.10', '3.11.4']` and it seems that dependabot is not configured to update that file. 

Could you please update the dependabot config?

**Comment by JWCook** [comment]
I do have dependabot set up to update actions: https://github.com/requests-cache/aiohttp-client-cache/blob/4e3c52344aeb59838352c74abec68d48718024eb/.github/dependabot.yml#L11-L16

But that won't automatically update python versions in the test matrix. Using 3.11.4 was specifically to avoid a regression bug introduced in 3.11.5. I'm not sure if that's fixed yet in 3.11.6, but I'll check.

**Comment by JWCook** [comment]
Looks like all tests pass with 3.11.7!
