### ISSUE TITLE
`datetime.utcnow` is deprecated

### ISSUE THREAD

**Issue by layday** [requests-cache/aiohttp-client-cache#237]
Hi, just a heads-up that `datetime.utcnow` was deprecated in Python 3.12.  `datetime.utcnow` is used in [several places](https://github.com/search?q=repo%3Arequests-cache%2Faiohttp-client-cache+utcnow&type=code) in `aiohttp-client-cache`. The [Python documentation](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcnow) recommends creating tz-aware datetime objects instead; a semantic equivalent would be `datetime.utc(timezone.utc).replace(tzinfo=None)`, if you'd like to keep working with "naive" datetimes instead.

**Comment by jamesbraza** [comment]
+1 to this. To share the full `DeprecationWarning`:

```none
/path/to/lib/python3.12/site-packages/aiohttp_client_cache/response.py:159: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
```
