### ISSUE TITLE
aiohttp 3.10 typed signature incompatibility

### ISSUE THREAD

**Issue by layday** [requests-cache/aiohttp-client-cache#248]
### The problem

aiohttp 3.10 added fine-grained types to the request wrapper methods' kwargs, which you can see [here](https://github.com/aio-libs/aiohttp/blob/7ffb847b9ff69c113cc077f6cb6ec50e3dfc62d8/aiohttp/client.py#L1034-L1077).  Currently, calls which specify `expire_after` do not type check. 

### Expected behavior

No type errors.

### Steps to reproduce the behavior

Type check e.g. `client.get('foo', expire_after=0)`.

### Workarounds

Call `request` instead of one of the wrapper methods, though the fact its kwargs are not typed is probably an oversight.

### Environment

- aiohttp-client-cache version: 0.11.0
- Python version: 3.11+
- Platform: n/a

**Comment by olk-m** [comment]
Thank you for opening an issue. 

I would like to clarify a few things to make sure we are talking about the same thing.


> No type errors.

Perhaps you wanted to say: Expected behavior: **to see** type errors?   

Because now Pyright works correctly

![aiohttp](https://github.com/user-attachments/assets/84437a52-f283-4953-8b67-f4ba8581c0f0)


but `Mypy` shows no warnings when I pass `fake_argument="foobar"`.



> `client.get('foo', expire_after=0)`

This is far a way from a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). It would be great to get a full snippet that can be copied and tested. 

Can you show a type error that you get? Are you talking about Mypy? About Pyright?

**Comment by olk-m** [comment]
@JWCook With `aiohttp==3.10.0`, do you know how to get Mypy to display the same warning as Pyright in my screenshot above?

**Comment by layday** [comment]
Yes, Pyright is behaving correctly based on the function's definition.  However, passing arbitrary keyword arguments to `session.get` and friends did not produce type errors prior to aiohttp 3.10, because they were annotated to accept `Any`. Now that their parameters are spelled out, passing `expire_after`, which is valid with a `CachedSession`, produces a type error.

**Comment by JWCook** [comment]
> By the way, `expire_after` is a backend argument. 

It isn't advertised in the docs, but it is possible to pass `expire_after` to request methods, which forwards it via `**kwargs` to [`CachedSession._request`](https://github.com/requests-cache/aiohttp-client-cache/blob/c97803ca41a1c78ea59d1dcfbe7479cf109905d7/aiohttp_client_cache/session.py#L62-L69). (added in #49)

@layday  I can see what you're talking about from looking at aiohttp's `client.py`. I'd be willing to add typed wrapper methods for `get()`, `post()`, etc. Is that something you'd like to submit a PR for?

I can't reproduce this locally, though. What mypy settings are you using? 

For example:
```py
from asyncio import run
from aiohttp_client_cache import CachedSession, SQLiteBackend

async def test():
    async with CachedSession(cache=SQLiteBackend('demo_cache')) as session:
        await session.get('http://httpbin.org/get', expire_after=360)

run(test())
```

```sh
$ pip install -U aiohttp-client-cache[sqlite] 'aiohttp>=3.10' mypy
$ mypy test.py
'Success: no issues found in 1 source file'
```

**Comment by JWCook** [comment]
As an aside, aiohttp's usage of `typing.Unpack` with a `TypedDict` is new to me! Looks like a nice way to reuse verbose function signatures. I'm currently doing something similar [here](https://github.com/requests-cache/aiohttp-client-cache/blob/main/aiohttp_client_cache/signatures.py) for the docs ([example](https://aiohttp-client-cache.readthedocs.io/en/latest/aiohttp_client_cache.session.html#aiohttp_client_cache.session.CachedSession._request)) using [python-forge](https://python-forge.readthedocs.io/en/latest/) , but I might like this approach better for simple cases like adding a single extra argument.

**Comment by layday** [comment]
https://github.com/requests-cache/aiohttp-client-cache/pull/249

**Comment by layday** [comment]
> I can't reproduce this locally, though. What mypy settings are you using?

I'm using Pyright. It looks like MyPy's not registering this as a type error, oddly.

**Comment by JWCook** [comment]
Your changes are in 0.11.1. Thanks!
